name: Test Coverage

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Updated to Node 20 LTS
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      # https://github.com/marketplace/actions/coveralls-github-action
      - name: Coveralls
        uses: coverallsapp/github-action@v2.2.3 # Pinned to a stable version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/marketplace/actions/code-climate-coverage-action
      - name: Code Climate
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload test artifacts
        if: always() # Run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: |
            coverage/
            *.log
