name: Push Images to Docker Hub

on:
  push:
    branches: [ master ]
  release:
    types: [ created, published, edited ]

env: 
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_TAG: ${{ github.event.release.tag_name }}
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache /var/lib/docker
      uses: actions/cache@v1
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-Dockerfile
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log into Docker Hub
      run: docker login --username $DOCKER_USER --password $DOCKER_PASS
      
    - name: Build image from Dockerfile
      run: docker build . --tag ideasonpurpose/docker-build
    
    - name: Deploy $LATEST image to Docker Hub
      run: docker push ideasonpurpose/docker-build
      
    - name: '[RELEASE] Tag image with release version'
      if: github.event == 'release'
      run: docker tag ideasonpurpose/docker-build ideasonpurpose/docker-build:$DOCKER_TAG
      
    - name: '[RELEASE] Deploy release-tagged image to Docker Hub'
      if: github.event == 'release'
      run: docker push ideasonpurpose/docker-build:$DOCKER_TAG

    - name: Reset permissions so caching works correctly
      run: |
        ls -la 
        ls -la ~
        echo ${{ github.workspace }}
        sudo chown -R $(whoami):$(id -ng) /var/lib/docker
