# This action will push version-tagged and latest images to Docker Hub
# It requires three secrets to be set:
#   DOCKER_USER: The Docker Hub username
#   DOCKER_PASS: The Docker Hub user's password
#   DOCKER_NAME: The full image name as it appears on Docker Hub

name: Push to Docker Hub

on:
  push:
    tags: ['v*'] 

env: 
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_NAME: ${{ secrets.DOCKER_NAME }}  
jobs:

  Deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build image from Dockerfile
      run: docker build . --tag $DOCKER_NAME
    
    - name: 'Tag image with version'
      run: docker tag $DOCKER_NAME ${DOCKER_NAME}:${GITHUB_REF#refs/tags/v}

    - name: 'Deploy  to Docker Hub'
      run: |
        docker login --username $DOCKER_USER --password $DOCKER_PASS
        docker push $DOCKER_NAME
        docker push ${DOCKER_NAME}:${GITHUB_REF#refs/tags/v}
