name: Push Images to Docker Hub

on:
  push:
    branches: [ master ]
    tags: ['v*'] 

env: 
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_TAG: ${{ github.event.release.tag_name }}
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Log into Docker Hub
      run: docker login --username $DOCKER_USER --password $DOCKER_PASS
      
    - name: Build image from Dockerfile
      run: docker build . --tag ideasonpurpose/docker-build
    
    - name: Deploy $LATEST image to Docker Hub
      run: docker push ideasonpurpose/docker-build
      
    - name: '[RELEASE] Tag image with release version'
      if: github.event == 'release'
      run: docker tag ideasonpurpose/docker-build ideasonpurpose/docker-build:$DOCKER_TAG
      
    - name: '[RELEASE] Deploy release-tagged image to Docker Hub'
      if: github.event == 'release'
      run: docker push ideasonpurpose/docker-build:$DOCKER_TAG
